2025-09-24 00:51:26 | INFO | __main__:41 | ✅ Access token actif jusqu’à 2025-09-24 06:23:02
2025-09-24 00:51:28 | INFO | __main__:27 | Page 1 récupérée (50 activités)
2025-09-24 00:51:30 | INFO | __main__:27 | Page 2 récupérée (50 activités)
2025-09-24 00:51:32 | INFO | __main__:27 | Page 3 récupérée (50 activités)
2025-09-24 00:51:32 | INFO | __main__:37 | ✅ 150 activités sauvegardées dans data/strava_activities.csv
2025-09-24 22:21:28 | INFO | __main__:86 | Lecture des activités: data/strava_activities.csv
2025-09-24 22:21:28 | INFO | __main__:93 | Filtrage vélo: 150 -> 86
2025-09-24 22:21:28 | INFO | __main__:119 | Début enrichissement météo sur 78 activités…
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=48.885918, lon=2.309292, when=2025-08-24 14:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=48.886097, lon=2.309522, when=2025-08-21 17:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=48.885807, lon=2.309932, when=2025-08-18 17:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=48.88472, lon=2.310837, when=2025-07-22 17:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=48.885941, lon=2.309598, when=2025-07-17 17:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=48.885986, lon=2.309545, when=2025-07-13 16:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=48.88599, lon=2.309363, when=2025-07-11 17:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=48.884796, lon=2.310757, when=2025-07-08 17:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=48.88488, lon=2.310717, when=2025-07-07 17:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=48.885978, lon=2.309338, when=2025-07-05 09:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=48.884582, lon=2.31134, when=2025-06-27 17:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=45.743328, lon=4.786422, when=2025-06-17 13:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=48.884972, lon=2.310732, when=2025-06-14 07:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=45.744289, lon=4.784968, when=2025-06-12 16:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=45.743599, lon=4.785984, when=2025-06-11 16:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=45.743553, lon=4.786082, when=2025-06-10 16:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.509628, lon=5.44581, when=2025-05-31 06:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.509632, lon=5.447238, when=2025-05-30 16:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=44.304285, lon=4.43247, when=2025-05-29 08:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=45.74449, lon=4.784271, when=2025-05-27 17:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=45.742554, lon=4.786135, when=2025-05-26 14:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=45.743526, lon=4.78605, when=2025-05-25 17:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=45.745908, lon=4.78401, when=2025-05-23 16:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=45.743378, lon=4.786383, when=2025-05-21 16:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.509064, lon=5.446688, when=2025-05-13 16:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.703162, lon=7.255289, when=2025-05-08 15:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.708988, lon=7.255728, when=2025-05-01 12:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.704155, lon=7.25612, when=2025-04-29 16:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.695728, lon=7.253797, when=2025-04-27 09:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:29 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.707684, lon=7.256113, when=2025-04-25 13:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.708576, lon=7.25593, when=2025-04-21 13:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.698189, lon=7.256045, when=2025-04-18 08:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=45.743279, lon=4.786147, when=2025-04-09 15:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=45.744522, lon=4.784093, when=2025-04-05 06:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=45.74334, lon=4.786123, when=2025-04-03 13:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.70792, lon=7.255988, when=2025-03-30 08:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.673626, lon=7.226952, when=2025-02-15 09:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.707489, lon=7.255963, when=2025-02-14 13:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.707798, lon=7.255993, when=2025-01-21 13:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.694065, lon=7.25629, when=2025-01-15 09:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=45.744358, lon=4.784848, when=2024-12-21 08:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=45.743546, lon=4.78609, when=2024-12-16 12:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.708435, lon=7.255727, when=2024-11-27 13:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.693523, lon=7.254897, when=2024-11-23 13:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.707516, lon=7.256038, when=2024-11-17 13:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.696102, lon=7.255742, when=2024-11-13 14:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.696472, lon=7.256455, when=2024-11-11 13:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.707047, lon=7.255747, when=2024-11-08 14:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.7079200707376, lon=7.255919957533479, when=2024-10-23 14:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.70883562602103, lon=7.25559851154685, when=2024-10-21 15:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.70488506741822, lon=7.2556735295802355, when=2024-10-19 07:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.69717723689973, lon=7.256143419072032, when=2024-10-15 15:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.71212770231068, lon=7.257523499429226, when=2024-10-03 12:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.70748898945749, lon=7.256018193438649, when=2024-09-30 15:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.69491957128048, lon=7.269899882376194, when=2024-09-25 18:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.546138778328896, lon=5.464518573135138, when=2024-08-05 15:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.546058647334576, lon=5.464523350819945, when=2024-07-17 16:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.54599377140403, lon=5.4644531942903996, when=2024-07-16 17:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.54613115079701, lon=5.4645118676126, when=2024-07-11 08:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=43.52480314671993, lon=5.435323230922222, when=2024-07-08 14:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=45.743632139638066, lon=4.785840734839439, when=2024-07-05 07:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=45.74429699219763, lon=4.7849183063954115, when=2024-07-03 12:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=45.7434577960521, lon=4.786216747015715, when=2024-06-30 05:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=50.462505323812366, lon=2.7999317552894354, when=2024-06-25 11:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=50.62908550724387, lon=3.043869948014617, when=2024-06-23 14:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=50.62924954108894, lon=3.0434500984847546, when=2024-06-19 14:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=50.62901308760047, lon=3.043473232537508, when=2024-06-15 07:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=50.629257168620825, lon=3.043416738510132, when=2024-06-12 13:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=50.62736512161791, lon=3.0413715541362762, when=2024-06-11 15:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=50.629058852791786, lon=3.0433900002390146, when=2024-06-09 16:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=50.629001604393125, lon=3.0436966102570295, when=2024-06-08 13:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=50.62873455695808, lon=3.043664926663041, when=2024-06-06 14:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=50.629001604393125, lon=3.0432150699198246, when=2024-06-04 15:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=50.6333770416677, lon=1.5794316865503788, when=2024-06-02 09:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=50.56196976453066, lon=2.8282967023551464, when=2024-06-02 04:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=50.62527081929147, lon=3.0393049959093332, when=2024-06-01 09:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=50.63040926121175, lon=3.047305103391409, when=2024-05-30 14:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | ERROR | __main__:76 | Erreur Meteostat pour lat=50.62900663353503, lon=3.0433491803705692, when=2024-05-29 15:00:00+00:00
Traceback (most recent call last):
  File "/Users/noah/projets/forecast_power/weather_enrich.py", line 56, in get_hourly_weather
    df_wx = Hourly(loc, when_utc, when_utc).fetch()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/hourly.py", line 147, in __init__
    self._init_time_series(loc, start, end, model, flags)
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/timeseries.py", line 176, in _init_time_series
    stations = loc.get_stations("daily", start, end, model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noah/projets/forecast_power/.venv/lib/python3.11/site-packages/meteostat/interface/point.py", line 90, in get_stations
    age = (datetime.now() - end).days
           ~~~~~~~~~~~~~~~^~~~~
  File "pandas/_libs/tslibs/timestamps.pyx", line 546, in pandas._libs.tslibs.timestamps._Timestamp.__rsub__
  File "pandas/_libs/tslibs/timestamps.pyx", line 514, in pandas._libs.tslibs.timestamps._Timestamp.__sub__
TypeError: Cannot subtract tz-naive and tz-aware datetime-like objects.
2025-09-24 22:21:30 | INFO | __main__:143 | ✅ Enrichi: 78 activités → data/strava_activities_weather.csv (météo manquante: 78)
2025-09-24 22:33:07 | INFO | __main__:92 | Lecture des activités: data/strava_activities.csv
2025-09-24 22:33:07 | INFO | __main__:99 | Filtrage vélo: 150 -> 86
2025-09-24 22:33:07 | INFO | __main__:125 | Début enrichissement météo sur 78 activités…
2025-09-24 22:43:00 | INFO | __main__:110 | Lecture des activités: data/strava_activities.csv
2025-09-24 22:43:00 | INFO | __main__:117 | Filtrage vélo: 150 -> 86
2025-09-24 22:43:00 | INFO | __main__:143 | Début enrichissement météo sur 78 activités…
2025-09-24 22:43:19 | INFO | __main__:167 | ✅ Enrichi: 78 activités → data/strava_activities_weather.csv (météo manquante: 0)
